sudo: required
language: python
services:
        - docker

before_script:
        - pip install docker-compose
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
        - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com 

script:
        - cd build; chmod +x build.sh ; ./build.sh
        - docker-compose run "docker-compose.yml"
        #- docker bui
        #- docker build -t aabhusan/koora:v2 .
        #- docker tag aabhusan/koora:v2 registry.heroku.com/$HEROKU_APP/web 
          
deploy:   
        provider: script
        script: 
               #docker push tradind/bourse:v2;
               docker push registry.heroku.com/$HEROKU_APP/web;
               heroku container:release web --app $HEROKU_APP
        on:
          branch: master